version: '3'
services:
  backend-service:
    build: .
    ports:
      - 7777:7777
    restart: always
    container_name: backend-service
    hostname: backend-service
    networks:
      - amazon-hoffe
    volumes:
      - .:/src
    command: ./scripts/start-dev.sh

networks:
  amazon-hoffe: